import{a as g,S as h,i as v}from"./assets/vendor-CtT2CgVQ.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))d(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&d(l)}).observe(document,{childList:!0,subtree:!0});function t(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function d(r){if(r.ep)return;r.ep=!0;const s=t(r);fetch(r.href,s)}})();const b="49472693-e26774e5dc97a1dde6aa5a0a9",w="https://pixabay.com/api/";async function p(o){const e=new URLSearchParams({key:b,q:o,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:c,page:i});try{const t=await g.get(`${w}?${e}`);return{photos:t.data.hits,totalHits:t.data.totalHits}}catch(t){throw console.error("Error:",t),t}}const y=document.querySelector(".gallery");document.querySelector(".btn");let L=new h(".gallery a",{captionsData:"alt",captionDelay:250});function S(){y.innerHTML=""}function q(){v.show({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",color:"red"})}function m(o){if(o.length===0){q();return}const e=o.map(t=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${t.largeImageURL}">
          <img class="gallery-image" src="${t.webformatURL}" alt="${t.tags}" />
        </a>
        <div class="gallery-info">
          <div><p>Likes</p><p>${t.likes}</p></div>
          <div><p>Views</p><p>${t.views}</p></div>
          <div><p>Comments</p><p>${t.comments}</p></div>
          <div><p>Downloads</p><p>${t.downloads}</p></div>
        </div>
      </li>
    `).join("");y.insertAdjacentHTML("beforeend",e),L.refresh(),E()}function E(){const o=document.querySelector(".gallery-item");if(o){const e=o.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}}let i=1,c=15,a="",f=1;const n=document.querySelector(".btn"),u=document.querySelector(".loader");async function P(o){if(o.preventDefault(),a=document.querySelector("input[name='search-text']").value.trim(),!!a){S(),u.style.display="inline-block",n.style.display="none";try{i=1;const e=await p(a,i);m(e.photos),f=Math.ceil(e.totalHits/c),n.style.display=e.totalHits>c?"inline-block":"none"}catch(e){console.error("Error:",e)}finally{u.style.display="none"}}}document.querySelector("form").addEventListener("submit",P);n.addEventListener("click",async()=>{try{i+=1;const o=await p(a,i);m(o.photos),i>=f&&(iziToast.error({position:"topRight",message:"We're sorry, but you've reached the end of search results."}),n.style.display="none")}catch(o){console.error("Error:",o)}});
//# sourceMappingURL=index.js.map
